Metrics/LineLength:
  Max: 120

Style/SymbolArray:
  AutoCorrect: false
Style/WordArray:
  AutoCorrect: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Metrics:
  Severity: refactor

# Metrics/AbcSize:
#   Enabled: false

# Metrics/BlockLength:
#   Enabled: false

Metrics/ClassLength:
  Enabled: false

# Metrics/CyclomaticComplexity:
#   Enabled: false

Metrics/MethodLength:
  Max: 15
#   Enabled: false

# Metrics/PerceivedComplexity:
#   Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
